language: bash
branches:
  only:
    - master
    - test
services:
  - docker
after_success:
  - bash -x .travis-deploy.sh
notifications:
  slack:
    secure: vJa+PrnS5lUcwL1v9XHQXMHhk6ZghXyMBP6HtRyLgg1iSQrxngFTjXXYVXJtu9cQzKhdoFdxjoN4EYU7yEVs9uqOUu0YqHTEqZw+FI4IDuotVvbdSb7FQCMnLLscToLKEe6sracs3l6LT7Gs5ujXVqNpeQGVmdLao4yS+bJPkcDGXP0M4x87NSh/zqdHqNK38+OT4AGhdPFOMVbA2ILRKQqvpsHIVEa9aFahFUwyaA6jNA6LZnLI7/hV1QSMjFaGGgRHoThWvroYP9z5oRQrCVQyfMvATqlMCirahNy7K6XvTmrn56OpWIwrXbSz9mbbwd8Fepl6enX/KEz1/NCvbCKhKSLxO5+PN+YSwAkP4B8asH4CEYwCaESPVLYrztSv+Q7rrZJZ7XXLhR/b3M97XUG8NEdkhxnPhTiTWGlxkiZ6Dbn6Emkc6Eq4RNR3oScbkOA7CdZ0THvD/WefjwT87dwgmrS1HngvYuDHd1U1fzGG+0rNpLPdSh+hxKxfRZVslRfm8D8o72AIWno5gxCrJxBUlB+43NWsuCYzUGhWgPQRPZAXtQjbJUV07IZr42GYu8qyXCtnA8tctrrCSAPTGFG6m+bj/Da3M0ywTLTMRTOo2UxWlOT5TKTMp5y3hD6XcmvO7vIvfzGMMR91bKCKC8Z11MnOOxR7xFsAHbpa1jc=
