baseurl = "https://hassiumlabs.com/"
languageCode = "en-us"
title = "Hassium Labs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
googleAnalytics = "UA-85417237-1"

[params]
	# General information
	author = "Hassium Labs"
	description = "Open Source Labs"
	copyright = "Hassium Labs"

	# Repository
	provider = ""
	repo_url = "https://github.com/hassiumlabs"

	version = ""
	logo = "css logo"
	favicon = "images/favicon.png"

	permalink = "&nbsp;"

	# Custom assets
	custom_css = [ "stylesheets/hassiumlabs.css" ]
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "grey"
    	accent  = "yellow"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "hassiumlabs"
	github  = "hassiumlabs"
	email   = "info@hassiumlabs.com"

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true

[[menu.main]]
	Name = "Contributors"
	Weight = 0
	URL = "https://github.com/orgs/hassiumlabs/people"
